### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by FrancescoCrecchi** [zaburo-ch/Parametric-t-SNE-in-Keras#1]
`RuntimeWarning: invalid value encountered in true_divide` when testing your code with CIFAR-10.
Although it's just a warning I think it has some impact on the final 2d representation which appears to be quite messy compared to the one obtained by the non-parametric model.

**Comment by May4m** [comment]
I also discovered that. Increasing the batch size helped get cleaner. I think it's because the model is calculating P(i|j) on a batch while it should be on the entire dataset
